export const SettingsTaxesConstants = {
  CREATE_TAX: 'CREATE_TAX',
  CREATE_TAX_RESPONSE: 'CREATE_TAX_RESPONSE',
  UPDATE_TAX: 'UPDATE_TAX',
  UPDATE_TAX_RESPONSE: 'UPDATE_TAX_RESPONSE',
  DELETE_TAX: 'DELETE_TAX',
  DELETE_TAX_RESPONSE: 'DELETE_TAX_RESPONSE',
  RESET_CREATE_TAX_UI_FLAGS: 'RESET_CREATE_TAX_UI_FLAGS',
  RESET_UPDATE_TAX_UI_FLAGS: 'RESET_UPDATE_TAX_UI_FLAGS'
};
