export const LoginConstants = {
  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_RESPONSE: 'SIGNUP_RESPONSE',
  LOGIN_WITH_PASSWORD_REQUEST: 'LOGIN_WITH_PASSWORD_REQUEST',
  LOGIN_WITH_PASSWORD_RESPONSE: 'LOGIN_WITH_PASSWORD_RESPONSE',

  SIGNUP_WITH_MOBILE_REQUEST: 'SIGNUP_WITH_MOBILE_REQUEST',
  SIGNUP_WITH_MOBILE_RESPONCE: 'SIGNUP_WITH_MOBILE_RESPONCE',
  VERIFY_MOBILE_REQUEST: 'VERIFY_MOBILE_REQUEST',
  VERIFY_MOBILE_RESPONCE: 'VERIFY_MOBILE_RESPONCE',

  VERIFY_TWOWAYAUTH_REQUEST: 'VERIFY_TWOWAYAUTH_REQUEST',
  VERIFY_TWOWAYAUTH_RESPONSE: 'VERIFY_TWOWAYAUTH_RESPONSE',

  SIGNUP_WITH_EMAIL_REQUEST: 'SIGNUP_WITH_EMAIL_REQUEST',
  SIGNUP_WITH_EMAIL_RESPONCE: 'SIGNUP_WITH_EMAIL_RESPONCE',
  VERIFY_EMAIL_REQUEST: 'VERIFY_EMAIL_REQUEST',
  VERIFY_EMAIL_RESPONCE: 'VERIFY_EMAIL_RESPONCE',
  RESET_LOGIN_WITH_EMAIL_FLAGS: 'RESET_LOGIN_WITH_EMAIL_FLAGS',

  SIGNUP_WITH_GOOGLE_REQUEST: 'SIGNUP_WITH_GOOGLE_REQUEST',
  SIGNUP_WITH_GOOGLE_RESPONSE: 'SIGNUP_WITH_GOOGLE_RESPONSE',

  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_RESPONSE: 'FORGOT_PASSWORD_RESPONSE',
  RESET_FORGOT_PASSWORD_FLAGS: 'RESET_FORGOT_PASSWORD_FLAGS',
  RESET_PASSWORD_V2_REQUEST: 'RESET_PASSWORD_V2_REQUEST',
  RESET_PASSWORD_V2_RESPONSE: 'RESET_PASSWORD_V2_RESPONSE',
  RESET_RESET_PASSWORD_FLAGS: 'RESET_RESET_PASSWORD_FLAGS',

  RESET_LOGIN_OTP_FLAGS: 'RESET_LOGIN_OTP_FLAGS',

  SET_INITIAL_SESSION_STATE: 'SET_INITIAL_SESSION_STATE',
  LOGOUT: 'LOGOUT',
  RESET_LOGIN_STATE: 'RESET_LOGIN_STATE',

  LinkedInLoginElectron: 'LinkedInLoginElectron'
}
