export const ReportConst = {
  PROFIT_LOSS_CHART: {
    GET_INCOME_DATA_REQUEST: 'GET_INCOME_DATA_REQUEST',
    GET_INCOME_DATA_RESPONSE: 'GET_INCOME_DATA_RESPONSE',
    GET_INCOME_DATA_ERROR: 'GET_INCOME_DATA_ERROR',

    GET_EXPENSES_DATA_REQUEST: 'GET_EXPENSES_DATA_REQUEST',
    GET_EXPENSES_DATA_RESPONSE: 'GET_EXPENSES_DATA_RESPONSE',
    GET_EXPENSES_DATA_ERROR: 'GET_EXPENSES_DATA_ERROR'
  },
  SET_REPORT_FILTER_TYPE: 'SET_REPORT_FILTER_TYPE'
};
