export const SettingsProfileConstants = {
 GET_PROFILE_RESPONSE: 'GET_PROFILE_RESPONSE',
 UPDATE_PROFILE: 'UPDATE_PROFILE',
 UPDATE_PROFILE_RESPONSE: 'UPDATE_PROFILE_RESPONSE',
  RESET_UPDATE_PROFILE_UI_FLAGS: 'RESET_UPDATE_PROFILE_UI_FLAGS'
};
