export const GeneralConst = {
  SET_COUNTRIES_WITH_CODES: 'SET_COUNTRIES_WITH_CODES',
  GET_ALL_STATES: 'GET_ALL_STATES',
  GET_ALL_STATES_RESPONSE: 'GET_ALL_STATES_RESPONSE',
  GET_FLATTEN_ACCOUNTS: 'GENERAL_GET_FLATTEN_ACCOUNTS',
  GET_FLATTEN_ACCOUNTS_RESPONSE: 'GENERAL_GET_FLATTEN_ACCOUNTS_RESPONSE',
}
