export const CompanyConstants = {
  CREATE_COMPANY: 'CREATE_COMPANY',
  CREATE_COMPANY_RESPONSE: 'CREATE_COMPANY_RESPONSE',
  RESET_CREATE_COMPANY_FLAG: 'RESET_CREATE_COMPANY_FLAG',

  REFRESH_COMPANIES: 'REFRESH_COMPANIES',
  REFRESH_COMPANIES_RESPONSE: 'REFRESH_COMPANIES_RESPONSE',

  GET_STATE_DETAILS: 'GET_STATE_DETAILS',
  GET_STATE_DETAILS_RESPONSE: 'GET_STATE_DETAILS_RESPONSE',
  SET_STATE_DETAILS: 'SET_STATE_DETAILS',
  SET_STATE_DETAILS_RESPONSE: 'SET_STATE_DETAILS_RESPONSE',

  CHANGE_COMPANY: 'CHANGE_COMPANY',
  CHANGE_COMPANY_RESPONSE: 'CHANGE_COMPANY_RESPONSE',

  SET_CONTACT_NO: 'SET_CONTACT_NO',

  DELETE_COMPANY: 'DELETE_COMPANY',
  DELETE_COMPANY_RESPONSE: 'DELETE_COMPANY_RESPONSE',

  GET_COMPANY_TAX : 'GET_COMPANY_TAX',
  GET_COMPANY_TAX_RESPONSE : 'GET_COMPANY_TAX_RESPONSE'
}
